### ISSUE TITLE
How to persist between requests?

### ISSUE THREAD

**Issue by IanMitchell** [microauth/microauth-twitter#2]
Hey, following up [per your tweet](https://twitter.com/paloskin/status/859289755267330048). 

I'm a little confused on functionality here, and was hoping for some clarification! Is this lib meant to only authorize the first request after a twitter user signs in? When I run the example, if I visit `/` it says no auth. If you go to `/auth/twitter` it asks you to sign in with the app, and then redirects you to the callback with the relevant auth information. But then if you try to go back to `/` the auth is no longer present.

Is this intended? I'm unclear if the library is meant to authorize only the first request after you log in with Twitter (current behavior) or each request you make afterwards (maybe a bug?)

**Comment by dimapaloskin** [comment]
Hello Ian. Good question!

> Is this lib meant to only authorize the first request after a twitter user signs in?

Yes, exactly.

The reason for that is very simple. Each project has a different from other way to keep authorization state. For example you can use jwt or just generate token and save it into the cookie. Also someone might want to keep tokens into redis for example or use own access and refresh tokens. So I can't force any of the listed methods :)

You need to implement this part manually according to your project approaches. Hope I explained clearly enough :)

**Comment by IanMitchell** [comment]
Yup! Just making sure, thanks!
